# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage ""
  version "0.0.5"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gleamsoda/donut/releases/download/v0.0.5/donut_Darwin_arm64.tar.gz"
      sha256 "1ad7513e45c847ed8d7b4ecb03fd4f958dc4cf37e3838f5a0ff7ce9ab35ebcc1"

      def install
        bin.install "donut"
        generate_completions_from_executable(bin/"donut", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
