# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage ""
  version "0.0.4"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gleamsoda/donut/releases/download/v0.0.4/donut_Darwin_arm64.tar.gz"
      sha256 "8f68143fda2f80a25b1d8ed3ac4ed2b77c1407ec817a5c58cb5cf51e422c1591"

      def install
        bin.install "donut"
        generate_completions_from_executable(bin/"donut", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
