# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donut < Formula
  desc "Tiny dotfiles management tool written in Go."
  homepage ""
  version "0.0.3"
  license "MIT"
  depends_on :macos

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/gleamsoda/donut/releases/download/v0.0.3/donut_Darwin_arm64.tar.gz"
      sha256 "be7590eaef75927e782f5698400bcc6dfc94112cb27f4f4c26b0fd90302cbd7b"

      def install
        bin.install "donut"
        generate_completions_from_executable(bin/"donut", "completion", shells: [:bash, :zsh, :fish])
      end
    end
  end

  test do
    system "#{bin}/donut --version"
  end
end
